### ISSUE TITLE
Cannot read property split of undefined

### ISSUE THREAD

**Issue by oscarrc** [Edqe14/AzlyricScraper#4]
I'm encountering this issue while trying to fetch a lyric:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at String.format (@/node_modules/azlyrics-scraper/src/lyrics.js:6:31)
```

In order to solve this issue I've added the following line to `lyrics.js` [line 42](https://github.com/Edqe14/AzlyricScraper/blob/3b6e1f3c9a8dbd43be46e835346d59666af0899c/src/lyrics.js#L41):

```javascript
let lyrics = $('.row .col-xs-12 div').each((_, e) => {
    if($(e).attr('class')) return;
        else if(!$(e).html()) return; //I've added this line
        else {
            $(e).html().format().split('\n').forEach(t => lyric.push(t));
        };
    });
```

Hope that helps.

**Comment by Edqe14** [comment]
Hello, 
Thanks for reporting this issue! Can you open a pull request for this fix? Thank you
